apiVersion: v1
kind: Service
metadata:
  name: physioflow-web-nodeport
spec:
  type: NodePort
  selector:
    app: physioflow
    component: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30200

---
apiVersion: v1
kind: Service
metadata:
  name: physioflow-api-nodeport
spec:
  type: NodePort
  selector:
    app: physioflow
    component: api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30201
