apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: physioflow-staging

resources:
  - ../../base
  - nodeport-services.yaml
  - secrets.yaml

patches:
  - path: configmap-patch.yaml

images:
  - name: registry.trancloud.work:5000/physioflow-web
    newTag: staging
  - name: registry.trancloud.work:5000/physioflow-api
    newTag: staging

commonLabels:
  environment: staging
