apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - deployment-web.yaml
  - deployment-api.yaml
  - service-web.yaml
  - service-api.yaml
  - configmap.yaml

commonLabels:
  app: physioflow
